// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ble.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ble_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ble_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ble_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ble_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ble_2eproto;
class Ble_t;
struct Ble_tDefaultTypeInternal;
extern Ble_tDefaultTypeInternal _Ble_t_default_instance_;
class SwBle_t;
struct SwBle_tDefaultTypeInternal;
extern SwBle_tDefaultTypeInternal _SwBle_t_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Ble_t* Arena::CreateMaybeMessage<::Ble_t>(Arena*);
template<> ::SwBle_t* Arena::CreateMaybeMessage<::SwBle_t>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Ble_t final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Ble_t) */ {
 public:
  inline Ble_t() : Ble_t(nullptr) {}
  ~Ble_t() override;
  explicit PROTOBUF_CONSTEXPR Ble_t(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Ble_t(const Ble_t& from);
  Ble_t(Ble_t&& from) noexcept
    : Ble_t() {
    *this = ::std::move(from);
  }

  inline Ble_t& operator=(const Ble_t& from) {
    CopyFrom(from);
    return *this;
  }
  inline Ble_t& operator=(Ble_t&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Ble_t& default_instance() {
    return *internal_default_instance();
  }
  static inline const Ble_t* internal_default_instance() {
    return reinterpret_cast<const Ble_t*>(
               &_Ble_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Ble_t& a, Ble_t& b) {
    a.Swap(&b);
  }
  inline void Swap(Ble_t* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Ble_t* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Ble_t* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Ble_t>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Ble_t& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Ble_t& from) {
    Ble_t::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ble_t* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Ble_t";
  }
  protected:
  explicit Ble_t(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSwFieldNumber = 1,
    kSyncFieldNumber = 2,
  };
  // .SwBle_t sw = 1;
  bool has_sw() const;
  private:
  bool _internal_has_sw() const;
  public:
  void clear_sw();
  const ::SwBle_t& sw() const;
  PROTOBUF_NODISCARD ::SwBle_t* release_sw();
  ::SwBle_t* mutable_sw();
  void set_allocated_sw(::SwBle_t* sw);
  private:
  const ::SwBle_t& _internal_sw() const;
  ::SwBle_t* _internal_mutable_sw();
  public:
  void unsafe_arena_set_allocated_sw(
      ::SwBle_t* sw);
  ::SwBle_t* unsafe_arena_release_sw();

  // bool sync = 2;
  void clear_sync();
  bool sync() const;
  void set_sync(bool value);
  private:
  bool _internal_sync() const;
  void _internal_set_sync(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Ble_t)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::SwBle_t* sw_;
    bool sync_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ble_2eproto;
};
// -------------------------------------------------------------------

class SwBle_t final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SwBle_t) */ {
 public:
  inline SwBle_t() : SwBle_t(nullptr) {}
  ~SwBle_t() override;
  explicit PROTOBUF_CONSTEXPR SwBle_t(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SwBle_t(const SwBle_t& from);
  SwBle_t(SwBle_t&& from) noexcept
    : SwBle_t() {
    *this = ::std::move(from);
  }

  inline SwBle_t& operator=(const SwBle_t& from) {
    CopyFrom(from);
    return *this;
  }
  inline SwBle_t& operator=(SwBle_t&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SwBle_t& default_instance() {
    return *internal_default_instance();
  }
  static inline const SwBle_t* internal_default_instance() {
    return reinterpret_cast<const SwBle_t*>(
               &_SwBle_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SwBle_t& a, SwBle_t& b) {
    a.Swap(&b);
  }
  inline void Swap(SwBle_t* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SwBle_t* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SwBle_t* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SwBle_t>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SwBle_t& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SwBle_t& from) {
    SwBle_t::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SwBle_t* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SwBle_t";
  }
  protected:
  explicit SwBle_t(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDeviceIDFieldNumber = 15,
    kEndpointFieldNumber = 16,
    kStatusFieldNumber = 17,
  };
  // uint32 deviceID = 15;
  void clear_deviceid();
  uint32_t deviceid() const;
  void set_deviceid(uint32_t value);
  private:
  uint32_t _internal_deviceid() const;
  void _internal_set_deviceid(uint32_t value);
  public:

  // uint32 endpoint = 16;
  void clear_endpoint();
  uint32_t endpoint() const;
  void set_endpoint(uint32_t value);
  private:
  uint32_t _internal_endpoint() const;
  void _internal_set_endpoint(uint32_t value);
  public:

  // bool status = 17;
  void clear_status();
  bool status() const;
  void set_status(bool value);
  private:
  bool _internal_status() const;
  void _internal_set_status(bool value);
  public:

  // @@protoc_insertion_point(class_scope:SwBle_t)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t deviceid_;
    uint32_t endpoint_;
    bool status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ble_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Ble_t

// .SwBle_t sw = 1;
inline bool Ble_t::_internal_has_sw() const {
  return this != internal_default_instance() && _impl_.sw_ != nullptr;
}
inline bool Ble_t::has_sw() const {
  return _internal_has_sw();
}
inline void Ble_t::clear_sw() {
  if (GetArenaForAllocation() == nullptr && _impl_.sw_ != nullptr) {
    delete _impl_.sw_;
  }
  _impl_.sw_ = nullptr;
}
inline const ::SwBle_t& Ble_t::_internal_sw() const {
  const ::SwBle_t* p = _impl_.sw_;
  return p != nullptr ? *p : reinterpret_cast<const ::SwBle_t&>(
      ::_SwBle_t_default_instance_);
}
inline const ::SwBle_t& Ble_t::sw() const {
  // @@protoc_insertion_point(field_get:Ble_t.sw)
  return _internal_sw();
}
inline void Ble_t::unsafe_arena_set_allocated_sw(
    ::SwBle_t* sw) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.sw_);
  }
  _impl_.sw_ = sw;
  if (sw) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Ble_t.sw)
}
inline ::SwBle_t* Ble_t::release_sw() {
  
  ::SwBle_t* temp = _impl_.sw_;
  _impl_.sw_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::SwBle_t* Ble_t::unsafe_arena_release_sw() {
  // @@protoc_insertion_point(field_release:Ble_t.sw)
  
  ::SwBle_t* temp = _impl_.sw_;
  _impl_.sw_ = nullptr;
  return temp;
}
inline ::SwBle_t* Ble_t::_internal_mutable_sw() {
  
  if (_impl_.sw_ == nullptr) {
    auto* p = CreateMaybeMessage<::SwBle_t>(GetArenaForAllocation());
    _impl_.sw_ = p;
  }
  return _impl_.sw_;
}
inline ::SwBle_t* Ble_t::mutable_sw() {
  ::SwBle_t* _msg = _internal_mutable_sw();
  // @@protoc_insertion_point(field_mutable:Ble_t.sw)
  return _msg;
}
inline void Ble_t::set_allocated_sw(::SwBle_t* sw) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.sw_;
  }
  if (sw) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(sw);
    if (message_arena != submessage_arena) {
      sw = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sw, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.sw_ = sw;
  // @@protoc_insertion_point(field_set_allocated:Ble_t.sw)
}

// bool sync = 2;
inline void Ble_t::clear_sync() {
  _impl_.sync_ = false;
}
inline bool Ble_t::_internal_sync() const {
  return _impl_.sync_;
}
inline bool Ble_t::sync() const {
  // @@protoc_insertion_point(field_get:Ble_t.sync)
  return _internal_sync();
}
inline void Ble_t::_internal_set_sync(bool value) {
  
  _impl_.sync_ = value;
}
inline void Ble_t::set_sync(bool value) {
  _internal_set_sync(value);
  // @@protoc_insertion_point(field_set:Ble_t.sync)
}

// -------------------------------------------------------------------

// SwBle_t

// uint32 deviceID = 15;
inline void SwBle_t::clear_deviceid() {
  _impl_.deviceid_ = 0u;
}
inline uint32_t SwBle_t::_internal_deviceid() const {
  return _impl_.deviceid_;
}
inline uint32_t SwBle_t::deviceid() const {
  // @@protoc_insertion_point(field_get:SwBle_t.deviceID)
  return _internal_deviceid();
}
inline void SwBle_t::_internal_set_deviceid(uint32_t value) {
  
  _impl_.deviceid_ = value;
}
inline void SwBle_t::set_deviceid(uint32_t value) {
  _internal_set_deviceid(value);
  // @@protoc_insertion_point(field_set:SwBle_t.deviceID)
}

// uint32 endpoint = 16;
inline void SwBle_t::clear_endpoint() {
  _impl_.endpoint_ = 0u;
}
inline uint32_t SwBle_t::_internal_endpoint() const {
  return _impl_.endpoint_;
}
inline uint32_t SwBle_t::endpoint() const {
  // @@protoc_insertion_point(field_get:SwBle_t.endpoint)
  return _internal_endpoint();
}
inline void SwBle_t::_internal_set_endpoint(uint32_t value) {
  
  _impl_.endpoint_ = value;
}
inline void SwBle_t::set_endpoint(uint32_t value) {
  _internal_set_endpoint(value);
  // @@protoc_insertion_point(field_set:SwBle_t.endpoint)
}

// bool status = 17;
inline void SwBle_t::clear_status() {
  _impl_.status_ = false;
}
inline bool SwBle_t::_internal_status() const {
  return _impl_.status_;
}
inline bool SwBle_t::status() const {
  // @@protoc_insertion_point(field_get:SwBle_t.status)
  return _internal_status();
}
inline void SwBle_t::_internal_set_status(bool value) {
  
  _impl_.status_ = value;
}
inline void SwBle_t::set_status(bool value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:SwBle_t.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ble_2eproto
