// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zigbee.proto

#include "zigbee.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR Zigbee_t::Zigbee_t(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.sw_)*/nullptr
  , /*decltype(_impl_.sync_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Zigbee_tDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Zigbee_tDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Zigbee_tDefaultTypeInternal() {}
  union {
    Zigbee_t _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Zigbee_tDefaultTypeInternal _Zigbee_t_default_instance_;
PROTOBUF_CONSTEXPR SwZb_t::SwZb_t(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.deviceid_)*/uint64_t{0u}
  , /*decltype(_impl_.endpoint_)*/0u
  , /*decltype(_impl_.status_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SwZb_tDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SwZb_tDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SwZb_tDefaultTypeInternal() {}
  union {
    SwZb_t _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SwZb_tDefaultTypeInternal _SwZb_t_default_instance_;
static ::_pb::Metadata file_level_metadata_zigbee_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_zigbee_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_zigbee_2eproto = nullptr;

const uint32_t TableStruct_zigbee_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Zigbee_t, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Zigbee_t, _impl_.sw_),
  PROTOBUF_FIELD_OFFSET(::Zigbee_t, _impl_.sync_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::SwZb_t, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::SwZb_t, _impl_.deviceid_),
  PROTOBUF_FIELD_OFFSET(::SwZb_t, _impl_.endpoint_),
  PROTOBUF_FIELD_OFFSET(::SwZb_t, _impl_.status_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Zigbee_t)},
  { 8, -1, -1, sizeof(::SwZb_t)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_Zigbee_t_default_instance_._instance,
  &::_SwZb_t_default_instance_._instance,
};

const char descriptor_table_protodef_zigbee_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014zigbee.proto\"-\n\010Zigbee_t\022\023\n\002sw\030\001 \001(\0132\007"
  ".SwZb_t\022\014\n\004sync\030\002 \001(\010\"<\n\006SwZb_t\022\020\n\010devic"
  "eID\030\001 \001(\004\022\020\n\010endpoint\030\002 \001(\r\022\016\n\006status\030\003 "
  "\001(\010b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_zigbee_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_zigbee_2eproto = {
    false, false, 131, descriptor_table_protodef_zigbee_2eproto,
    "zigbee.proto",
    &descriptor_table_zigbee_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_zigbee_2eproto::offsets,
    file_level_metadata_zigbee_2eproto, file_level_enum_descriptors_zigbee_2eproto,
    file_level_service_descriptors_zigbee_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_zigbee_2eproto_getter() {
  return &descriptor_table_zigbee_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_zigbee_2eproto(&descriptor_table_zigbee_2eproto);

// ===================================================================

class Zigbee_t::_Internal {
 public:
  static const ::SwZb_t& sw(const Zigbee_t* msg);
};

const ::SwZb_t&
Zigbee_t::_Internal::sw(const Zigbee_t* msg) {
  return *msg->_impl_.sw_;
}
Zigbee_t::Zigbee_t(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Zigbee_t)
}
Zigbee_t::Zigbee_t(const Zigbee_t& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Zigbee_t* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.sw_){nullptr}
    , decltype(_impl_.sync_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_sw()) {
    _this->_impl_.sw_ = new ::SwZb_t(*from._impl_.sw_);
  }
  _this->_impl_.sync_ = from._impl_.sync_;
  // @@protoc_insertion_point(copy_constructor:Zigbee_t)
}

inline void Zigbee_t::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.sw_){nullptr}
    , decltype(_impl_.sync_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Zigbee_t::~Zigbee_t() {
  // @@protoc_insertion_point(destructor:Zigbee_t)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Zigbee_t::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.sw_;
}

void Zigbee_t::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Zigbee_t::Clear() {
// @@protoc_insertion_point(message_clear_start:Zigbee_t)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.sw_ != nullptr) {
    delete _impl_.sw_;
  }
  _impl_.sw_ = nullptr;
  _impl_.sync_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Zigbee_t::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .SwZb_t sw = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_sw(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool sync = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.sync_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Zigbee_t::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Zigbee_t)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .SwZb_t sw = 1;
  if (this->_internal_has_sw()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::sw(this),
        _Internal::sw(this).GetCachedSize(), target, stream);
  }

  // bool sync = 2;
  if (this->_internal_sync() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_sync(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Zigbee_t)
  return target;
}

size_t Zigbee_t::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Zigbee_t)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .SwZb_t sw = 1;
  if (this->_internal_has_sw()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.sw_);
  }

  // bool sync = 2;
  if (this->_internal_sync() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Zigbee_t::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Zigbee_t::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Zigbee_t::GetClassData() const { return &_class_data_; }


void Zigbee_t::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Zigbee_t*>(&to_msg);
  auto& from = static_cast<const Zigbee_t&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Zigbee_t)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_sw()) {
    _this->_internal_mutable_sw()->::SwZb_t::MergeFrom(
        from._internal_sw());
  }
  if (from._internal_sync() != 0) {
    _this->_internal_set_sync(from._internal_sync());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Zigbee_t::CopyFrom(const Zigbee_t& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Zigbee_t)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Zigbee_t::IsInitialized() const {
  return true;
}

void Zigbee_t::InternalSwap(Zigbee_t* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Zigbee_t, _impl_.sync_)
      + sizeof(Zigbee_t::_impl_.sync_)
      - PROTOBUF_FIELD_OFFSET(Zigbee_t, _impl_.sw_)>(
          reinterpret_cast<char*>(&_impl_.sw_),
          reinterpret_cast<char*>(&other->_impl_.sw_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Zigbee_t::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_zigbee_2eproto_getter, &descriptor_table_zigbee_2eproto_once,
      file_level_metadata_zigbee_2eproto[0]);
}

// ===================================================================

class SwZb_t::_Internal {
 public:
};

SwZb_t::SwZb_t(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:SwZb_t)
}
SwZb_t::SwZb_t(const SwZb_t& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SwZb_t* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.deviceid_){}
    , decltype(_impl_.endpoint_){}
    , decltype(_impl_.status_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.deviceid_, &from._impl_.deviceid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.status_) -
    reinterpret_cast<char*>(&_impl_.deviceid_)) + sizeof(_impl_.status_));
  // @@protoc_insertion_point(copy_constructor:SwZb_t)
}

inline void SwZb_t::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.deviceid_){uint64_t{0u}}
    , decltype(_impl_.endpoint_){0u}
    , decltype(_impl_.status_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SwZb_t::~SwZb_t() {
  // @@protoc_insertion_point(destructor:SwZb_t)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SwZb_t::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SwZb_t::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SwZb_t::Clear() {
// @@protoc_insertion_point(message_clear_start:SwZb_t)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.deviceid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.status_) -
      reinterpret_cast<char*>(&_impl_.deviceid_)) + sizeof(_impl_.status_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SwZb_t::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 deviceID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.deviceid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 endpoint = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.endpoint_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool status = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SwZb_t::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SwZb_t)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 deviceID = 1;
  if (this->_internal_deviceid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_deviceid(), target);
  }

  // uint32 endpoint = 2;
  if (this->_internal_endpoint() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_endpoint(), target);
  }

  // bool status = 3;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_status(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SwZb_t)
  return target;
}

size_t SwZb_t::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SwZb_t)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 deviceID = 1;
  if (this->_internal_deviceid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_deviceid());
  }

  // uint32 endpoint = 2;
  if (this->_internal_endpoint() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_endpoint());
  }

  // bool status = 3;
  if (this->_internal_status() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SwZb_t::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SwZb_t::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SwZb_t::GetClassData() const { return &_class_data_; }


void SwZb_t::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SwZb_t*>(&to_msg);
  auto& from = static_cast<const SwZb_t&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SwZb_t)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_deviceid() != 0) {
    _this->_internal_set_deviceid(from._internal_deviceid());
  }
  if (from._internal_endpoint() != 0) {
    _this->_internal_set_endpoint(from._internal_endpoint());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SwZb_t::CopyFrom(const SwZb_t& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SwZb_t)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SwZb_t::IsInitialized() const {
  return true;
}

void SwZb_t::InternalSwap(SwZb_t* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SwZb_t, _impl_.status_)
      + sizeof(SwZb_t::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(SwZb_t, _impl_.deviceid_)>(
          reinterpret_cast<char*>(&_impl_.deviceid_),
          reinterpret_cast<char*>(&other->_impl_.deviceid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SwZb_t::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_zigbee_2eproto_getter, &descriptor_table_zigbee_2eproto_once,
      file_level_metadata_zigbee_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Zigbee_t*
Arena::CreateMaybeMessage< ::Zigbee_t >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Zigbee_t >(arena);
}
template<> PROTOBUF_NOINLINE ::SwZb_t*
Arena::CreateMaybeMessage< ::SwZb_t >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SwZb_t >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
