// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zigbee.proto

#ifndef PROTOBUF_INCLUDED_zigbee_2eproto
#define PROTOBUF_INCLUDED_zigbee_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_zigbee_2eproto 

namespace protobuf_zigbee_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_zigbee_2eproto
class SwZb_t;
class SwZb_tDefaultTypeInternal;
extern SwZb_tDefaultTypeInternal _SwZb_t_default_instance_;
class Zigbee_t;
class Zigbee_tDefaultTypeInternal;
extern Zigbee_tDefaultTypeInternal _Zigbee_t_default_instance_;
namespace google {
namespace protobuf {
template<> ::SwZb_t* Arena::CreateMaybeMessage<::SwZb_t>(Arena*);
template<> ::Zigbee_t* Arena::CreateMaybeMessage<::Zigbee_t>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class Zigbee_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Zigbee_t) */ {
 public:
  Zigbee_t();
  virtual ~Zigbee_t();

  Zigbee_t(const Zigbee_t& from);

  inline Zigbee_t& operator=(const Zigbee_t& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Zigbee_t(Zigbee_t&& from) noexcept
    : Zigbee_t() {
    *this = ::std::move(from);
  }

  inline Zigbee_t& operator=(Zigbee_t&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Zigbee_t& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Zigbee_t* internal_default_instance() {
    return reinterpret_cast<const Zigbee_t*>(
               &_Zigbee_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Zigbee_t* other);
  friend void swap(Zigbee_t& a, Zigbee_t& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Zigbee_t* New() const final {
    return CreateMaybeMessage<Zigbee_t>(NULL);
  }

  Zigbee_t* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Zigbee_t>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Zigbee_t& from);
  void MergeFrom(const Zigbee_t& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Zigbee_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .SwZb_t sw = 1;
  bool has_sw() const;
  void clear_sw();
  static const int kSwFieldNumber = 1;
  private:
  const ::SwZb_t& _internal_sw() const;
  public:
  const ::SwZb_t& sw() const;
  ::SwZb_t* release_sw();
  ::SwZb_t* mutable_sw();
  void set_allocated_sw(::SwZb_t* sw);

  // bool sync = 2;
  void clear_sync();
  static const int kSyncFieldNumber = 2;
  bool sync() const;
  void set_sync(bool value);

  // @@protoc_insertion_point(class_scope:Zigbee_t)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::SwZb_t* sw_;
  bool sync_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_zigbee_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SwZb_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SwZb_t) */ {
 public:
  SwZb_t();
  virtual ~SwZb_t();

  SwZb_t(const SwZb_t& from);

  inline SwZb_t& operator=(const SwZb_t& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SwZb_t(SwZb_t&& from) noexcept
    : SwZb_t() {
    *this = ::std::move(from);
  }

  inline SwZb_t& operator=(SwZb_t&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SwZb_t& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SwZb_t* internal_default_instance() {
    return reinterpret_cast<const SwZb_t*>(
               &_SwZb_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(SwZb_t* other);
  friend void swap(SwZb_t& a, SwZb_t& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SwZb_t* New() const final {
    return CreateMaybeMessage<SwZb_t>(NULL);
  }

  SwZb_t* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SwZb_t>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SwZb_t& from);
  void MergeFrom(const SwZb_t& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SwZb_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool status = 17;
  void clear_status();
  static const int kStatusFieldNumber = 17;
  bool status() const;
  void set_status(bool value);

  // uint32 deviceID = 15;
  void clear_deviceid();
  static const int kDeviceIDFieldNumber = 15;
  ::google::protobuf::uint32 deviceid() const;
  void set_deviceid(::google::protobuf::uint32 value);

  // uint32 endpoint = 16;
  void clear_endpoint();
  static const int kEndpointFieldNumber = 16;
  ::google::protobuf::uint32 endpoint() const;
  void set_endpoint(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:SwZb_t)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool status_;
  ::google::protobuf::uint32 deviceid_;
  ::google::protobuf::uint32 endpoint_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_zigbee_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Zigbee_t

// .SwZb_t sw = 1;
inline bool Zigbee_t::has_sw() const {
  return this != internal_default_instance() && sw_ != NULL;
}
inline void Zigbee_t::clear_sw() {
  if (GetArenaNoVirtual() == NULL && sw_ != NULL) {
    delete sw_;
  }
  sw_ = NULL;
}
inline const ::SwZb_t& Zigbee_t::_internal_sw() const {
  return *sw_;
}
inline const ::SwZb_t& Zigbee_t::sw() const {
  const ::SwZb_t* p = sw_;
  // @@protoc_insertion_point(field_get:Zigbee_t.sw)
  return p != NULL ? *p : *reinterpret_cast<const ::SwZb_t*>(
      &::_SwZb_t_default_instance_);
}
inline ::SwZb_t* Zigbee_t::release_sw() {
  // @@protoc_insertion_point(field_release:Zigbee_t.sw)
  
  ::SwZb_t* temp = sw_;
  sw_ = NULL;
  return temp;
}
inline ::SwZb_t* Zigbee_t::mutable_sw() {
  
  if (sw_ == NULL) {
    auto* p = CreateMaybeMessage<::SwZb_t>(GetArenaNoVirtual());
    sw_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Zigbee_t.sw)
  return sw_;
}
inline void Zigbee_t::set_allocated_sw(::SwZb_t* sw) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete sw_;
  }
  if (sw) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      sw = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, sw, submessage_arena);
    }
    
  } else {
    
  }
  sw_ = sw;
  // @@protoc_insertion_point(field_set_allocated:Zigbee_t.sw)
}

// bool sync = 2;
inline void Zigbee_t::clear_sync() {
  sync_ = false;
}
inline bool Zigbee_t::sync() const {
  // @@protoc_insertion_point(field_get:Zigbee_t.sync)
  return sync_;
}
inline void Zigbee_t::set_sync(bool value) {
  
  sync_ = value;
  // @@protoc_insertion_point(field_set:Zigbee_t.sync)
}

// -------------------------------------------------------------------

// SwZb_t

// uint32 deviceID = 15;
inline void SwZb_t::clear_deviceid() {
  deviceid_ = 0u;
}
inline ::google::protobuf::uint32 SwZb_t::deviceid() const {
  // @@protoc_insertion_point(field_get:SwZb_t.deviceID)
  return deviceid_;
}
inline void SwZb_t::set_deviceid(::google::protobuf::uint32 value) {
  
  deviceid_ = value;
  // @@protoc_insertion_point(field_set:SwZb_t.deviceID)
}

// uint32 endpoint = 16;
inline void SwZb_t::clear_endpoint() {
  endpoint_ = 0u;
}
inline ::google::protobuf::uint32 SwZb_t::endpoint() const {
  // @@protoc_insertion_point(field_get:SwZb_t.endpoint)
  return endpoint_;
}
inline void SwZb_t::set_endpoint(::google::protobuf::uint32 value) {
  
  endpoint_ = value;
  // @@protoc_insertion_point(field_set:SwZb_t.endpoint)
}

// bool status = 17;
inline void SwZb_t::clear_status() {
  status_ = false;
}
inline bool SwZb_t::status() const {
  // @@protoc_insertion_point(field_get:SwZb_t.status)
  return status_;
}
inline void SwZb_t::set_status(bool value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:SwZb_t.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_zigbee_2eproto
