// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `wifi.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

// @@protoc_insertion_point(message:Zigbee_t)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Zigbee_t {
    // message fields
    // @@protoc_insertion_point(field:Zigbee_t.sw)
    pub sw: ::protobuf::MessageField<SwZb_t>,
    // @@protoc_insertion_point(field:Zigbee_t.sync)
    pub sync: bool,
    // special fields
    // @@protoc_insertion_point(special_field:Zigbee_t.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Zigbee_t {
    fn default() -> &'a Zigbee_t {
        <Zigbee_t as ::protobuf::Message>::default_instance()
    }
}

impl Zigbee_t {
    pub fn new() -> Zigbee_t {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, SwZb_t>(
            "sw",
            |m: &Zigbee_t| { &m.sw },
            |m: &mut Zigbee_t| { &mut m.sw },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sync",
            |m: &Zigbee_t| { &m.sync },
            |m: &mut Zigbee_t| { &mut m.sync },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Zigbee_t>(
            "Zigbee_t",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Zigbee_t {
    const NAME: &'static str = "Zigbee_t";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.sw)?;
                },
                16 => {
                    self.sync = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.sw.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.sync != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.sw.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if self.sync != false {
            os.write_bool(2, self.sync)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Zigbee_t {
        Zigbee_t::new()
    }

    fn clear(&mut self) {
        self.sw.clear();
        self.sync = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Zigbee_t {
        static instance: Zigbee_t = Zigbee_t {
            sw: ::protobuf::MessageField::none(),
            sync: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Zigbee_t {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Zigbee_t").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Zigbee_t {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Zigbee_t {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:SwZb_t)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SwZb_t {
    // message fields
    // @@protoc_insertion_point(field:SwZb_t.deviceID)
    pub deviceID: u32,
    // @@protoc_insertion_point(field:SwZb_t.endpoint)
    pub endpoint: u32,
    // @@protoc_insertion_point(field:SwZb_t.status)
    pub status: bool,
    // special fields
    // @@protoc_insertion_point(special_field:SwZb_t.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SwZb_t {
    fn default() -> &'a SwZb_t {
        <SwZb_t as ::protobuf::Message>::default_instance()
    }
}

impl SwZb_t {
    pub fn new() -> SwZb_t {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "deviceID",
            |m: &SwZb_t| { &m.deviceID },
            |m: &mut SwZb_t| { &mut m.deviceID },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "endpoint",
            |m: &SwZb_t| { &m.endpoint },
            |m: &mut SwZb_t| { &mut m.endpoint },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "status",
            |m: &SwZb_t| { &m.status },
            |m: &mut SwZb_t| { &mut m.status },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SwZb_t>(
            "SwZb_t",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SwZb_t {
    const NAME: &'static str = "SwZb_t";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                120 => {
                    self.deviceID = is.read_uint32()?;
                },
                128 => {
                    self.endpoint = is.read_uint32()?;
                },
                136 => {
                    self.status = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.deviceID != 0 {
            my_size += ::protobuf::rt::uint32_size(15, self.deviceID);
        }
        if self.endpoint != 0 {
            my_size += ::protobuf::rt::uint32_size(16, self.endpoint);
        }
        if self.status != false {
            my_size += 2 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.deviceID != 0 {
            os.write_uint32(15, self.deviceID)?;
        }
        if self.endpoint != 0 {
            os.write_uint32(16, self.endpoint)?;
        }
        if self.status != false {
            os.write_bool(17, self.status)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SwZb_t {
        SwZb_t::new()
    }

    fn clear(&mut self) {
        self.deviceID = 0;
        self.endpoint = 0;
        self.status = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SwZb_t {
        static instance: SwZb_t = SwZb_t {
            deviceID: 0,
            endpoint: 0,
            status: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SwZb_t {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SwZb_t").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SwZb_t {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SwZb_t {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\nwifi.proto\"7\n\x08Zigbee_t\x12\x17\n\x02sw\x18\x01\x20\x01(\x0b2\
    \x07.SwZb_tR\x02sw\x12\x12\n\x04sync\x18\x02\x20\x01(\x08R\x04sync\"X\n\
    \x06SwZb_t\x12\x1a\n\x08deviceID\x18\x0f\x20\x01(\rR\x08deviceID\x12\x1a\
    \n\x08endpoint\x18\x10\x20\x01(\rR\x08endpoint\x12\x16\n\x06status\x18\
    \x11\x20\x01(\x08R\x06statusJ\xa0\x03\n\x06\x12\x04\0\0\x0b\x01\n\x08\n\
    \x01\x0c\x12\x03\0\0\x12\n\n\n\x02\x04\0\x12\x04\x02\0\x05\x01\n\n\n\x03\
    \x04\0\x01\x12\x03\x02\x08\x10\n\x0b\n\x04\x04\0\x02\0\x12\x03\x03\x02\
    \x0f\n\r\n\x05\x04\0\x02\0\x04\x12\x04\x03\x02\x02\x12\n\x0c\n\x05\x04\0\
    \x02\0\x06\x12\x03\x03\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x03\t\
    \x0b\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x03\r\x0e\n\x0b\n\x04\x04\0\x02\
    \x01\x12\x03\x04\x02\x0f\n\r\n\x05\x04\0\x02\x01\x04\x12\x04\x04\x02\x03\
    \x0f\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x04\x02\x06\n\x0c\n\x05\x04\0\
    \x02\x01\x01\x12\x03\x04\x07\x0b\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\
    \x04\r\x0e\n\n\n\x02\x04\x01\x12\x04\x07\0\x0b\x01\n\n\n\x03\x04\x01\x01\
    \x12\x03\x07\x08\x0e\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x08\x02\x15\n\r\n\
    \x05\x04\x01\x02\0\x04\x12\x04\x08\x02\x07\x10\n\x0c\n\x05\x04\x01\x02\0\
    \x05\x12\x03\x08\x02\x08\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x08\t\x11\
    \n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x08\x12\x14\n\x0b\n\x04\x04\x01\
    \x02\x01\x12\x03\t\x02\x15\n\r\n\x05\x04\x01\x02\x01\x04\x12\x04\t\x02\
    \x08\x15\n\x0c\n\x05\x04\x01\x02\x01\x05\x12\x03\t\x02\x08\n\x0c\n\x05\
    \x04\x01\x02\x01\x01\x12\x03\t\t\x11\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\
    \x03\t\x12\x14\n\x0b\n\x04\x04\x01\x02\x02\x12\x03\n\x02\x12\n\r\n\x05\
    \x04\x01\x02\x02\x04\x12\x04\n\x02\t\x15\n\x0c\n\x05\x04\x01\x02\x02\x05\
    \x12\x03\n\x02\x06\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x03\n\x07\r\n\x0c\
    \n\x05\x04\x01\x02\x02\x03\x12\x03\n\x0f\x11b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(Zigbee_t::generated_message_descriptor_data());
            messages.push(SwZb_t::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
