# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: typedef.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtypedef.proto\">\n\x05Led_t\x12\x0c\n\x04name\x18\x10 \x01(\t\x12\x0b\n\x03mac\x18\x11 \x01(\x04\x12\n\n\x02\x65p\x18\x12 \x01(\r\x12\x0e\n\x06status\x18\x13 \x01(\x08\"3\n\x06Sync_t\x12\x0b\n\x03\x61\x64\x64\x18\x10 \x01(\x08\x12\x0e\n\x06remove\x18\x11 \x01(\x08\x12\x0c\n\x04sync\x18\x12 \x01(\x08\"=\n\x04Sw_t\x12\x0c\n\x04name\x18\x10 \x01(\t\x12\n\n\x02\x65p\x18\x11 \x01(\r\x12\x0b\n\x03mac\x18\x12 \x01(\x04\x12\x0e\n\x06status\x18\x13 \x01(\x08\"7\n\x05Ota_t\x12\x11\n\tcheck_ota\x18\x10 \x01(\x08\x12\x0e\n\x06status\x18\x11 \x01(\x08\x12\x0b\n\x03\x61\x63k\x18\x12 \x01(\x08\"&\n\x0bKeepAlive_t\x12\x17\n\x06sender\x18\x01 \x01(\x0e\x32\x07.User_t\"C\n\x07Timer_t\x12\x0b\n\x03\x64\x61y\x18\x0f \x01(\r\x12\r\n\x05month\x18\x10 \x01(\r\x12\x0c\n\x04hour\x18\x11 \x01(\r\x12\x0e\n\x06minute\x18\x12 \x01(\r\"\xea\x01\n\x06\x42uffer\x12\x0f\n\x07mac_hub\x18\x01 \x01(\t\x12\x17\n\x06sender\x18\x02 \x01(\x0e\x32\x07.User_t\x12\x19\n\x08receiver\x18\x03 \x01(\x0e\x32\x07.User_t\x12\x1a\n\tcotroller\x18\x04 \x01(\x0e\x32\x07.User_t\x12\x15\n\x04sync\x18\x05 \x01(\x0b\x32\x07.Sync_t\x12\x13\n\x03ota\x18\x10 \x01(\x0b\x32\x06.Ota_t\x12\x13\n\x03vpn\x18\x11 \x01(\x0b\x32\x06.Vpn_t\x12\x13\n\x03led\x18\x12 \x03(\x0b\x32\x06.Led_t\x12\x11\n\x02sw\x18\x13 \x03(\x0b\x32\x05.Sw_t\x12\x16\n\x04time\x18\x14 \x01(\x0b\x32\x08.Timer_t\"$\n\x05Vpn_t\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03mac\x18\x02 \x01(\t\"9\n\x08Vendor_t\x12\x0f\n\x07mac_ven\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08*b\n\x06User_t\x12\x07\n\x03\x41pp\x10\x00\x12\n\n\x06Server\x10\x01\x12\x07\n\x03Hub\x10\x02\x12\n\n\x06Zigbee\x10\x03\x12\x07\n\x03\x42le\x10\x04\x12\x06\n\x02\x41i\x10\x05\x12\x08\n\x04Wifi\x10\x06\x12\n\n\x06Screen\x10\x07\x12\x07\n\x03Ota\x10\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'typedef_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER_T._serialized_start=697
  _USER_T._serialized_end=795
  _LED_T._serialized_start=17
  _LED_T._serialized_end=79
  _SYNC_T._serialized_start=81
  _SYNC_T._serialized_end=132
  _SW_T._serialized_start=134
  _SW_T._serialized_end=195
  _OTA_T._serialized_start=197
  _OTA_T._serialized_end=252
  _KEEPALIVE_T._serialized_start=254
  _KEEPALIVE_T._serialized_end=292
  _TIMER_T._serialized_start=294
  _TIMER_T._serialized_end=361
  _BUFFER._serialized_start=364
  _BUFFER._serialized_end=598
  _VPN_T._serialized_start=600
  _VPN_T._serialized_end=636
  _VENDOR_T._serialized_start=638
  _VENDOR_T._serialized_end=695
# @@protoc_insertion_point(module_scope)
